import Link from "next/link";
import { BeaconLogo } from "@/components/beacon-logo";

export const metadata = {
  title: "Terms of Service — Beacon",
  description: "The terms governing your use of Beacon.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <BeaconLogo href="/" />
          <Link href="/login" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            Sign in
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="prose prose-slate max-w-none">
          <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
          <p className="text-muted-foreground text-sm mb-8">Effective Date: April 27, 2026 · Last Updated: April 27, 2026</p>

          <Section title="1. Acceptance of Terms">
            <p>By creating a Beacon account or using the Beacon platform in any way, you agree to be bound by these Terms of Service. If you are creating an account on behalf of an insurance agency or other organization, you represent and warrant that you have the authority to bind that organization to these Terms.</p>
            <p>If you do not agree to these Terms, do not create an account or use Beacon.</p>
          </Section>

          <Section title="2. Who Can Use Beacon">
            <p>Beacon is intended exclusively for use by licensed insurance agents, brokers, and agencies. By creating an account, you represent and warrant that:</p>
            <ul>
              <li>You hold all licenses required by your state and applicable law to conduct insurance business</li>
              <li>You will use Beacon only in connection with your licensed insurance activities</li>
              <li>All information you provide during registration is accurate and complete</li>
              <li>You are at least 18 years of age</li>
            </ul>
          </Section>

          <Section title="3. AI-Generated Content — Critical Terms">
            <p>Beacon uses artificial intelligence to generate draft letters and client communications. <strong>This is the most important section of these Terms. Please read it carefully.</strong></p>
            <p>By using Beacon's letter generation features, you acknowledge and agree to all of the following:</p>
            <ul>
              <li><strong>All AI-generated content is a draft only.</strong> Every letter Beacon generates is a starting point for your review — not a finished, ready-to-send document.</li>
              <li><strong>You are solely responsible for reviewing every letter before sending it.</strong></li>
              <li><strong>You are solely responsible for the accuracy of all communications.</strong> You must verify that all information in a generated letter is accurate before sending.</li>
              <li><strong>You are solely responsible for regulatory compliance.</strong> You must ensure that any communication sent through Beacon complies with all applicable state and federal laws.</li>
              <li><strong>Beacon is a drafting tool, not a licensed professional.</strong> Nothing generated by Beacon constitutes legal advice, regulatory guidance, or professional insurance advice of any kind.</li>
              <li><strong>Your professional responsibility cannot be transferred to Beacon.</strong></li>
              <li><strong>Beacon does not guarantee output quality.</strong> AI-generated letters may contain errors, inaccuracies, or hallucinations. You are responsible for catching and correcting these issues before sending.</li>
            </ul>
          </Section>

          <Section title="4. E&O Documentation Log">
            <p>The E&amp;O documentation log maintained by Beacon is provided as a convenience feature to help you track client communications. You acknowledge and agree that:</p>
            <ul>
              <li>Beacon makes no representation that this log satisfies any particular regulatory, legal, E&amp;O carrier, or compliance requirement</li>
              <li>You are solely responsible for maintaining all records required by your state insurance department, your E&amp;O carrier, and applicable law</li>
              <li>The log records when letters were generated and sent through Beacon but cannot verify what communications occurred outside of Beacon</li>
            </ul>
          </Section>

          <Section title="5. Email Integration">
            <p>When you connect a Gmail or Outlook account to Beacon:</p>
            <ul>
              <li>You authorize Beacon to send emails on your behalf through that connected account</li>
              <li>You remain solely responsible for all communications sent through your connected email account</li>
              <li>Beacon does not read, store, or index the existing content of your email account</li>
              <li>You may disconnect your email account at any time from your account settings</li>
            </ul>
          </Section>

          <Section title="6. Client Data">
            <p>By uploading client information into Beacon, you represent and warrant that:</p>
            <ul>
              <li>You have all necessary rights, permissions, and legal basis to upload and process that client information</li>
              <li>Your use of client data within Beacon complies with all applicable privacy laws and your professional obligations to your clients</li>
              <li>You have disclosed to your clients, as required by applicable law, that their information may be processed by third-party software tools used in your practice</li>
            </ul>
          </Section>

          <Section title="7. Acceptable Use">
            <p>You agree not to use Beacon to:</p>
            <ul>
              <li>Generate communications that are false, misleading, deceptive, or fraudulent</li>
              <li>Generate communications that violate any applicable law or regulation</li>
              <li>Attempt to circumvent, disable, or interfere with any security feature of the platform</li>
              <li>Access or attempt to access any other user's account or data</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of Beacon</li>
              <li>Use Beacon for any purpose other than your licensed insurance business activities</li>
              <li>Resell, sublicense, or provide access to Beacon to any third party without written permission</li>
            </ul>
          </Section>

          <Section title="8. Subscription and Billing">
            <p><strong>Subscriptions:</strong> Beacon offers monthly subscription plans as described on the pricing page. By subscribing, you authorize Beacon to charge your payment method on a recurring basis.</p>
            <p><strong>Auto-renewal:</strong> Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date.</p>
            <p><strong>Free trial:</strong> Free trial letters are provided as described on the pricing page. Upon using all free trial letters, a paid subscription is required to continue.</p>
            <p><strong>Cancellation:</strong> You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period.</p>
            <p><strong>Refunds:</strong> Payments are non-refundable except where required by applicable law.</p>
            <p><strong>Price changes:</strong> Beacon reserves the right to change subscription pricing with at least 30 days written notice to active subscribers delivered by email.</p>
          </Section>

          <Section title="9. Intellectual Property">
            <p><strong>Your content:</strong> You retain all ownership of the client data, letter content, and agency information you provide to Beacon.</p>
            <p><strong>Beacon's platform:</strong> The Beacon platform, including its software, design, AI prompts, and all related intellectual property, is owned by Scott Figeroa d/b/a Monolith. Nothing in these Terms transfers ownership of Beacon's intellectual property to you.</p>
          </Section>

          <Section title="10. Confidentiality">
            <p>Beacon treats all agency data and client information as confidential. We will not disclose your data or your clients' data to third parties except as described in our Privacy Policy or as required by law.</p>
          </Section>

          <Section title="11. Termination">
            <p><strong>By you:</strong> You may cancel your account at any time from your account settings.</p>
            <p><strong>By Beacon:</strong> Beacon reserves the right to suspend or terminate accounts that violate these Terms, engage in fraudulent activity, or create legal or regulatory risk.</p>
            <p><strong>Effect of termination:</strong> Upon termination, your access to Beacon ends immediately. Your data is retained and deleted per the schedule described in the Privacy Policy.</p>
          </Section>

          <Section title="12. Disclaimers">
            <p className="uppercase text-xs leading-relaxed">Beacon is provided "as is" and "as available" without warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, non-infringement, or uninterrupted or error-free operation. Beacon does not warrant that AI-generated content will be accurate, complete, regulatory-compliant, or appropriate for any particular purpose or client.</p>
          </Section>

          <Section title="13. Limitation of Liability">
            <p className="uppercase text-xs leading-relaxed">To the maximum extent permitted by applicable law, Scott Figeroa d/b/a Monolith and its operators, employees, and contractors shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages. Beacon's total cumulative liability shall not exceed the total amount paid by you to Beacon in the three calendar months immediately preceding the event giving rise to the claim.</p>
          </Section>

          <Section title="14. Indemnification">
            <p>You agree to defend, indemnify, and hold harmless Scott Figeroa d/b/a Monolith from any claims arising from your use of Beacon, any letter you send through Beacon, your violation of these Terms, or your violation of any applicable law or professional obligation.</p>
          </Section>

          <Section title="15. Governing Law and Disputes">
            <p>These Terms are governed by the laws of the State of Utah. Any dispute that cannot be resolved informally shall be subject to the exclusive jurisdiction of the state and federal courts located in Utah. Before initiating any legal proceeding, you agree to contact us at <a href="mailto:legal@get-monolith.com" className="underline">legal@get-monolith.com</a> and attempt to resolve the dispute informally for at least 30 days.</p>
          </Section>

          <Section title="16. Changes to These Terms">
            <p>We will notify account holders by email at least 30 days before any material changes to these Terms take effect. Continued use of Beacon after changes take effect constitutes acceptance of the updated Terms.</p>
          </Section>

          <Section title="17. Contact">
            <p>Scott Figeroa d/b/a Monolith<br />Ogden, Utah, United States<br /><a href="mailto:legal@get-monolith.com" className="underline">legal@get-monolith.com</a></p>
          </Section>
        </div>
      </main>

      <footer className="border-t mt-16">
        <div className="max-w-3xl mx-auto px-6 py-6 flex items-center justify-between text-xs text-muted-foreground">
          <span>Beacon · A product of Monolith · Ogden, Utah</span>
          <div className="flex gap-4">
            <Link href="/privacy" className="hover:text-foreground">Privacy</Link>
            <Link href="/terms" className="hover:text-foreground">Terms</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-semibold mb-3">{title}</h2>
      <div className="text-sm leading-relaxed text-foreground/80 space-y-3">{children}</div>
    </section>
  );
}
